version: '3.1'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./public:/usr/src/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8080:80'
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
  db:
    image: mysql:5.7
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/dumps:/usr/app/dumps/
      - .docker/sql/init:/tmp/database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    command: mysqld --init-file="/tmp/database/init.sql"


